# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Increase memory for builds
org.gradle.jvmargs=-Xmx4608m -XX:MaxMetaspaceSize=1024m

# Enable parallel builds
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true


# For NDK debugging
android.native.buildOutput=verbose